START SETTINGS
CONTEXT pest_prep
#CONTEXT model_run
#CONTEXT all
DATE_FORMAT mm/dd/yyyy
END SETTINGS
#
##########################################
# Read time series from the statvar file #
##########################################
START GET_MUL_SERIES_STATVAR
CONTEXT all
FILE andcrk.statvar
DATE_1 10/01/2003
TIME_1 00:00:00
DATE_2 09/30/2004
TIME_2 00:00:00
VARIABLE_NAME ch_outlet_pH
LOCATION_ID 1
NEW_SERIES_NAME ph_s
VARIABLE_NAME ch_outlet_tempC
LOCATION_ID 1
NEW_SERIES_NAME tempc_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 1
NEW_SERIES_NAME Ca_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 2
NEW_SERIES_NAME Mg_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 3
NEW_SERIES_NAME Na_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 4
NEW_SERIES_NAME K_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 5
NEW_SERIES_NAME Amm_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 6
NEW_SERIES_NAME Alk_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 7
NEW_SERIES_NAME Cl_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 8
NEW_SERIES_NAME S_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 9
NEW_SERIES_NAME NO3_s
VARIABLE_NAME ch_outlet_mgL
LOCATION_ID 10
NEW_SERIES_NAME Si_s
VARIABLE_NAME ch_outlet_permil
LOCATION_ID 11
NEW_SERIES_NAME 18O_s
VARIABLE_NAME qbasincfs
LOCATION_ID 1
NEW_SERIES_NAME q_cfs_s
END GET_MUL_SERIES_STATVAR
#
#####################################
# Read time series from an ssf file #
#####################################
START GET_SERIES_SSF
CONTEXT all
FILE @PROJECT_DIR@AndHydObs.ssf
SITE q_cfs
NEW_SERIES_NAME q_cfs_o
DATE_1 10/01/2003
TIME_1 00:00:00
DATE_2 09/30/2004 
TIME_2 00:00:00
END GET_SERIES_SSF
#
##############################################
# Read multiple time series from an ssf file #
##############################################
START GET_MUL_SERIES_SSF
CONTEXT all
FILE @PROJECT_DIR@AndChemObs.ssf
DATE_1 10/01/2003
TIME_1 00:00:00
DATE_2 09/30/2004 
TIME_2 00:00:00
SITE tempc_obs
NEW_SERIES_NAME tempc_o
SITE pH_obs
NEW_SERIES_NAME ph_o
SITE Ca_obs
NEW_SERIES_NAME Ca_o
SITE Mg_obs
NEW_SERIES_NAME Mg_o
SITE Na_obs
NEW_SERIES_NAME Na_o
SITE K_obs
NEW_SERIES_NAME K_o
SITE Amm_obs
NEW_SERIES_NAME Amm_o
SITE Alk_obs
NEW_SERIES_NAME Alk_o
SITE Cl_obs
NEW_SERIES_NAME Cl_o
SITE S_obs
NEW_SERIES_NAME S_o
SITE N(5)_obs
NEW_SERIES_NAME NO3_o
SITE Si_obs
NEW_SERIES_NAME Si_o
SITE [180]_obs
NEW_SERIES_NAME 18O_o
END GET_MUL_SERIES_SSF
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME ph_s
TB_SERIES_NAME ph_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME ph_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME ph_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME tempc_s
TB_SERIES_NAME tempc_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME tempc_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME tempc_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME Ca_s
TB_SERIES_NAME Ca_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME Ca_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME Ca_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME Mg_s
TB_SERIES_NAME Mg_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME Mg_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME Mg_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME Na_s
TB_SERIES_NAME Na_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME Na_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME Na_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME K_s
TB_SERIES_NAME K_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME K_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME K_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME Amm_s
TB_SERIES_NAME Amm_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME Amm_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME Amm_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME Alk_s
TB_SERIES_NAME Alk_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME Alk_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME Alk_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME Cl_s
TB_SERIES_NAME Cl_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME Cl_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME Cl_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME S_s
TB_SERIES_NAME S_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME S_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME S_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME NO3_s
TB_SERIES_NAME NO3_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME NO3_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME NO3_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME Si_s
TB_SERIES_NAME Si_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME Si_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME Si_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME 18O_s
TB_SERIES_NAME 18O_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME 18O_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME 18O_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#################################
# Resample the simulated series #
#################################
START NEW_TIME_BASE
CONTEXT all
SERIES_NAME q_cfs_s
TB_SERIES_NAME q_cfs_o
NEW_SERIES_NAME temp
END NEW_TIME_BASE
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME q_cfs_s
END ERASE_ENTITY
#
START SERIES_EQUATION
CONTEXT all
NEW_SERIES_NAME q_cfs_s
EQUATION temp
END SERIES_EQUATION
#
START ERASE_ENTITY
CONTEXT all
SERIES_NAME temp
END ERASE_ENTITY
#
#######################################
# Model results are written to a file #
#######################################
START LIST_OUTPUT
CONTEXT all
FILE andcrk_sim.out
SERIES_FORMAT long
SERIES_NAME ph_s
SERIES_NAME tempc_s
SERIES_NAME Ca_s
SERIES_NAME Mg_s
SERIES_NAME Na_s
SERIES_NAME K_s
SERIES_NAME Amm_s
SERIES_NAME Alk_s
SERIES_NAME Cl_s
SERIES_NAME S_s
SERIES_NAME NO3_s
SERIES_NAME Si_s
SERIES_NAME 18O_s
SERIES_NAME q_cfs_s
END LIST_OUTPUT_BLOCK
#
####################
# Write pest files #
####################
START WRITE_PEST_FILES
CONTEXT        pest_prep
NEW_PEST_CONTROL_FILE andcrk.pst
TRUNCATED_SVD 5e-7
TEMPLATE_FILE @PROJECT_DIR@par2par_andcrk.tpl
MODEL_INPUT_FILE  par2par_andcrk.dat
#TEMPLATE_FILE params_andcrk.tpl
#MODEL_INPUT_FILE  andcrk.params
#TEMPLATE_FILE params_andcrk.tpl
#MODEL_INPUT_FILE  andcrk.params
#TEMPLATE_FILE pqi_andcrk.tpl
#MODEL_INPUT_FILE  andcrk.dat.pqi
NEW_INSTRUCTION_FILE andcrk.ins
#
OBSERVATION_SERIES_NAME ph_o
MODEL_SERIES_NAME ph_s
SERIES_WEIGHTS_EQUATION 2.1
#
OBSERVATION_SERIES_NAME tempc_o
MODEL_SERIES_NAME tempc_s
SERIES_WEIGHTS_EQUATION 0.0
#
OBSERVATION_SERIES_NAME Ca_o
MODEL_SERIES_NAME Ca_s
SERIES_WEIGHTS_EQUATION 2.5
#
OBSERVATION_SERIES_NAME Mg_o
MODEL_SERIES_NAME Mg_s
SERIES_WEIGHTS_EQUATION 15.7
#
OBSERVATION_SERIES_NAME Na_o
MODEL_SERIES_NAME Na_s
SERIES_WEIGHTS_EQUATION 7.7
#
OBSERVATION_SERIES_NAME K_o
MODEL_SERIES_NAME K_s
SERIES_WEIGHTS_EQUATION 18.6
#
OBSERVATION_SERIES_NAME Amm_o
MODEL_SERIES_NAME Amm_s
SERIES_WEIGHTS_EQUATION 0.0
#
OBSERVATION_SERIES_NAME Alk_o
MODEL_SERIES_NAME Alk_s
SERIES_WEIGHTS_EQUATION 2.1
#
OBSERVATION_SERIES_NAME Cl_o
MODEL_SERIES_NAME Cl_s
SERIES_WEIGHTS_EQUATION 0.0
#
OBSERVATION_SERIES_NAME S_o
MODEL_SERIES_NAME S_s
SERIES_WEIGHTS_EQUATION 1.6
#
OBSERVATION_SERIES_NAME NO3_o
MODEL_SERIES_NAME NO3_s
SERIES_WEIGHTS_EQUATION 6.8
#
OBSERVATION_SERIES_NAME Si_o
MODEL_SERIES_NAME Si_s
SERIES_WEIGHTS_EQUATION 1.9
#
OBSERVATION_SERIES_NAME 18O_o
MODEL_SERIES_NAME 18O_s
SERIES_WEIGHTS_EQUATION 0.0
#
OBSERVATION_SERIES_NAME q_cfs_o
MODEL_SERIES_NAME q_cfs_s
#SERIES_WEIGHTS_EQUATION 0.0
SERIES_WEIGHTS_EQUATION 0.012002/@_abs_value+0.99945
SERIES_WEIGHTS_MIN_MAX 1.0 4.0
#
PARAMETER_DATA_FILE @PROJECT_DIR@pest_params_andcrk.txt
PARAMETER_GROUP_FILE @PROJECT_DIR@pest_groups_andcrk.txt
MODEL_COMMAND_LINE @PROJECT_DIR@pest_webmod.bat
END WRITE_PEST_FILES
