ptf %
# Par2par file for PRMS parameter estimation
* parameter data
CO2uz =  %    CO2uz     %
CO2str = %    CO2str    %
O2uz =   %    O2uz      %
O2str =  %    O2str     %
koligu = %    koligu    %
kbiotu = %    kbiotu    %
kchlru = %    kchlru    %
kcalcu = %    kcalcu    %
kpyr_u = %    kpyr_u    %
knitru = %    knitru    %
kK_sum = %    kK_sum    %
kK_win = %    kK_win    %
todays = %    todays    %
tudays = %    tudays    %
tsdays = %    tsdays    %
tocadj = %    tocadj    %
tucadj = %    tucadj    %
tscadj = %    tscadj    %
qdffrac = %    qdffrac   %
td     = %    td        %
adjmix = %    adjmix    %
candep = %    candep    %
ccvint = %    ccvint    %
ccvslp = %    ccvslp    %
chloss = %    chloss    %
chvelo = %    chvelo    %
cdensm = %    cdensm    %
cdenwn = %    cdenwn    %
crdcof = %    crdcof    %
crddexp = %    crddexp   %
daymlt = %    daymlt    %
pancof = %    pancof    %
gwloss = %    gwloss    %
isofac = %    isofac    %
meltba = %    meltba    %
meltmx = %    meltmx    %
nmeltf = %    nmeltf    %
pklwhc = %    pklwhc    %
pmacst = %    pmacst    %
pmacro = %    pmacro    %
pptrad = %    pptrad    %
radjsp = %    radjsp    %
radjwp = %    radjwp    %
radmax = %    radmax    %
rainad = %    rainad    %
s_ohor = %    s_ohor    %
s_thpo = %    s_thpo    %
s_thfc = %    s_thfc    %
awc    = %    awc       %
s_rock = %    s_rock    %
s_root = %    s_root    %
s_satk = %    s_satk    %
s_zmax = %    s_zmax    %
s_zmin = %    s_zmin    %
sn_thr = %    sn_thr    %
snadja = %    snadja    %
snadjb = %    snadjb    %
sn_int = %    sn_int    %
sn_ion = %    sn_ion    %
sO_dpl = %    sO_dpl    %
sD_dpl = %    sD_dpl    %
sraini = %    sraini    %
wraini = %    wraini    %
recess = %    recess    %
sn_flx = %    sn_flx    %
tmxadj = %    tmxadj    %
tmxalr = %    tmxalr    %
tmxals = %    tmxals    %
tmnadj = %    tmnadj    %
trdegc = %    trdegc    %
windad = %    windad    %
xkcvar = %    xkcvar    %
xkvert = %    xkvert    %
# Compute sn_5_6, the snow correction factor for MRUs 5-6, that receives extra snow in from the western slope 
sn_5_6 = snadja*snadjb
# Compute wilting point
s_thwp = s_thfc-awc
# T_decay = 0, original exponential decay, T0 (transm) not constrained by szm (shape factor)
#transm  =  recess
# T_decay = 1, parabolic decay with TL values from GIS
# sa is the slope of 1/sqrt(Q), Q in m3/hr for outlet, times the sqrt(area), area of basin in square meters
# homogeneous recess, szm, transm, To, varies as the square of lambda, the mean TTI
alpha = 8.6e-5
basarea = 1.74e6
sa = alpha * sqrt(basarea)
transm01  =  (recess*sa*78.0)**2
transm02  =  (recess*sa*111.7)**2
transm03  =  (recess*sa*36.5)**2
transm04  =  (recess*sa*125.9)**2
transm05  =  (recess*sa*65.8)**2
transm06  =  (recess*sa*84.0)**2
transm07  =  (recess*sa*90.5)**2
transm08  =  (recess*sa*102.6)**2
transm09  =  (recess*sa*43.6)**2
transm10  =  (recess*sa*54.3)**2
# T_decay = 2, linear decay
#transm  =  recess*92.72550721
# Distribute temp adjustment and melt factors according to slope and aspect
tmxadj01 = tmxadj+2.0
tmxadj02 = tmxadj-3.0
tmxadj03 = tmxadj+2.2
tmxadj04 = tmxadj-1.3
tmxadj05 = tmxadj+2.5
tmxadj06 = tmxadj-1.3
tmxadj07 = tmxadj-0.9
tmxadj08 = tmxadj-2.9
tmxadj09 = tmxadj-2.1
tmxadj10 = tmxadj-3.6
tmnadj01 = tmnadj+1.0
tmnadj02 = tmnadj-1.5
tmnadj03 = tmnadj+1.1
tmnadj04 = tmnadj-0.7
tmnadj05 = tmnadj+1.2
tmnadj06 = tmnadj-0.7
tmnadj07 = tmnadj-0.5
tmnadj08 = tmnadj-1.5
tmnadj09 = tmnadj-1.1
tmnadj10 = tmnadj-1.8
meltmx01 = meltmx*1.31
meltmx02 = meltmx*0.66
meltmx03 = meltmx*1.35
meltmx04 = meltmx*0.88
meltmx05 = meltmx*1.38
meltmx06 = meltmx*0.88
meltmx07 = meltmx*0.93
meltmx08 = meltmx*0.67
meltmx09 = meltmx*0.77
meltmx10 = meltmx*0.58
meltmn01 = meltmx01*0.43
meltmn02 = meltmx02*0.03
meltmn03 = meltmx03*0.47
meltmn04 = meltmx04*0.07
meltmn05 = meltmx05*0.4
meltmn06 = meltmx06*0.09
meltmn07 = meltmx07*0.03
meltmn08 = meltmx08*0.03
meltmn09 = meltmx09*0.08
meltmn10 = meltmx10*0.03

* template files
webmod.params.tpl webmod.params
webmod.pqi.tpl webmod.pqi
