#if defined(CMAKE_FC)
#define call_modules        call_modules_
#define control_string      control_string_
#define dattim              dattim_
#define decl_control        decl_control_
#define decldim             decldim_
#define declfix             declfix_
#define declmodule          declmodule_
#define declparam           declparam_
#define declpri             declpri_
#define declvar             declvar_
#define deltim              deltim_
#define djulian             djulian_
#define dpdble              dpdble_
#define dpint4              dpint4_
#define dpreal              dpreal_
#define dpstr               dpstr_
#define getdataname         getdataname_
#define getdim              getdim_
#define getdimname          getdimname_
#define getoutname          getoutname_
#define getparam            getparam_
#define getstep             getstep_
#define getvar              getvar_
#define isleap              isleap_
#define julian              julian_
#define opstr               opstr_
#define putvar              putvar_
#define readvar             readvar_
#endif
